provisionerName: "rawfile.csi.openebs.io"

defaults: &defaults
  image:
    repository: docker.io/openebs/rawfile-localpv
    tag: v0.12.0
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
  tolerations: []

controller:
  <<: *defaults

node:
  <<: *defaults
  metrics:
    enabled: false
  data_dir_path: /data

imagePullSecrets: []
serviceMonitor:
  enabled: false
  interval: 1m
