apiVersion: v1
kind: Service
metadata:
  name: {{ include "openebs-rawfile-localpv.fullname" . }}-controller
  labels:
    {{- include "openebs-rawfile-localpv.labels" . | nindent 4 }}
    component: controller
spec:
  type: ClusterIP
  selector:
    {{- include "openebs-rawfile-localpv.selectorLabels" . | nindent 4 }}
    component: controller
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openebs-rawfile-localpv.fullname" . }}-controller
spec:
  replicas: 1
  serviceName: {{ include "openebs-rawfile-localpv.fullname" . }}
  selector:
    matchLabels: &selectorLabels
      {{- include "openebs-rawfile-localpv.selectorLabels" . | nindent 6 }}
      component: controller
  template:
    metadata:
      labels: *selectorLabels
    spec:
      serviceAccount: {{ include "openebs-rawfile-localpv.fullname" . }}-driver
      priorityClassName: system-cluster-critical
      {{- with $values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: socket-dir
          emptyDir: {}
      containers:
        - name: csi-driver
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
            - csi-driver
            - --disable-metrics
          env:
            - name: PROVISIONER_NAME
              value: "{{ .Values.provisionerName }}"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: IMAGE_REPOSITORY
              value: "{{ .Values.controller.image.repository }}"
          {{- if regexMatch "^.*-ci$" .Values.controller.image.tag }}
            - name: IMAGE_TAG
              value: "{{ .Values.controller.image.tag }}"
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - name: csi-probe
              containerPort: 9808
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
        - name: external-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
