apiVersion: v2
name: graph-network-indexer
description: Deploy and scale the [Graph Network Indexer](https://github.com/graphprotocol/indexer) components inside Kubernetes with ease

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
version: 0.5.13
=======
version: 0.5.12
>>>>>>> 6a6d2f8 (chore(graph-network-indexer): new v)

# The appVersion field is intentionally left empty. Component versions are managed separately
# and can be found in the values.yaml file or individual component configurations.
appVersion: ""
