{{- $values := $.Values.heimdalld }}
{{- $componentName := "heimdalld" }}
{{- $componentLabel := include "polygon.componentLabelFor" $componentName }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polygon.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "polygon.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  genesis.json: |
    {{ (required "Invalid network specified" (.Files.Get (print "genesis/" $componentName "/" .Values.network ".json"))) | nindent 4 }}
